version: '3.9'

services:
  web: 
    image: nginx:latest  
    ports:
      - "8080:80"  
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - webnetwork  

  db: 
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: exampledb
    ports:
      - "5432:5432"  
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - webnetwork

networks:  
  webnetwork:

volumes:  
  dbdata:
